// Generated by CoffeeScript 1.10.0
(function() {
  var BaseChild, CustomerAddress, Metafields,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  BaseChild = require('./base_child');

  Metafields = require('./metafield');

  CustomerAddress = (function(superClass) {
    extend(CustomerAddress, superClass);

    CustomerAddress.prototype.parent = "/customers";

    CustomerAddress.prototype.slug = "addresses";

    CustomerAddress.prototype.child = "/addresses";

    function CustomerAddress(site) {
      CustomerAddress.__super__.constructor.call(this, site);
    }

    CustomerAddress.prototype.all = function(parentId, params, callback) {
      var url, _ref;
      if (typeof params === 'function') {
        _ref = [callback, params], params = _ref[0], callback = _ref[1];
      }
      url = this.resource.queryString("" + this.prefix + "/" + parentId + this.child, params);
      return this.resource.get(url, "" + this.slug, callback);
    };

    return CustomerAddress;

  })(BaseChild);

  module.exports = CustomerAddress;

}).call(this);
